export const demoSubscriptions = [
  {
    name: "Netflix",
    category: "Entertainment",
    price: 15.99,
    currency: "USD",
    billingCycle: "MONTHLY",
    billingInterval: 1,
    status: "ACTIVE",
    nextBillingDate: new Date("2026-04-08"),
    color: "#ef4444",
  },
  {
    name: "Spotify",
    category: "Music",
    price: 9.99,
    currency: "USD",
    billingCycle: "MONTHLY",
    billingInterval: 1,
    status: "ACTIVE",
    nextBillingDate: new Date("2026-04-12"),
    color: "#10b981",
  },
  {
    name: "Notion AI",
    category: "Productivity",
    price: 10,
    currency: "USD",
    billingCycle: "TRIAL",
    billingInterval: 1,
    status: "ACTIVE",
    nextBillingDate: new Date("2026-04-15"),
    trialEndsAt: new Date("2026-04-15"),
    color: "#111827",
  },
  {
    name: "iCloud+",
    category: "Cloud",
    price: 2.99,
    currency: "USD",
    billingCycle: "MONTHLY",
    billingInterval: 1,
    status: "ACTIVE",
    nextBillingDate: new Date("2026-04-18"),
    color: "#0ea5e9",
  },
];
